### PR TITLE
Update JFR image to 210413_777e270

### PR DESCRIPTION
**Pull request by alxsap**
### Description

Updated JFR image to 210413_777e270 with `agentProtocols` config & latest ES plugin (actually no real changes in the plugin):
https://github.com/SAP/stewardci-jenkinsfilerunner-image/compare/210205_1988c5e...210413_777e270

### Submitter checklist

- [x] Change has been tested (on a back-end cluster)
- [x] (If applicable) Jira backlog item ID added to the PR title and the [changelog.yaml] entry
- [x] [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change)
- [x] Semantic version diffed against [last release][releases] and updated accordingly. In this project the version has to be maintained here:
    - [/charts/steward/Chart.yaml](https://github.com/SAP/stewardci-core/blob/master/charts/steward/Chart.yaml) (`version` and `appVersion`)

In case dependencies have been updated:
- [x] Links to external changelogs, since the last release of our component, added to the [changelog.yaml] entry (description).
- [x] Changelogs read thoroughly, potential impact described, upgrade notes prepared (if necessary)
- [x] Check if dependency updates affect our semantic version increment.

### Reviewer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There is at least 1 approval for the pull request and no outstanding requests for change
- [ ] All voter checks have passed
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] The Pull Request title is understandable and reflects the changes well
- [ ] The Pull Request description is understandable and well documented
- [ ] [changelog.yaml] entry for this Pull Request has been added
    - [ ] Changelog entry contains all required information
    - [ ] 'Upgrade notes' are documented in changelog.yaml (if required)

[changelog.yaml]: https://github.com/SAP/stewardci-core/changelog.yaml
[releases]: https://github.com/SAP/stewardci-core/releases

### CODE REVIEW

**Comment by alxsap** [comment]
Tests ongoing

**Comment by alxsap** [comment]
Validated successfully

**Comment by alxsap** [comment]
Changelog missing

**Review by rinckm — APPROVED** [review]
lgtm

**Pull request merged**
